### PR TITLE
Update todo.txt

### PR DESCRIPTION
**Pull request by MirrorImage**

### CODE REVIEW

**Comment by sylvia43** [comment]
No. I don't have any of those things you checked off.

**Comment by MirrorImage** [comment]
Well yeah, I'm working on the sounds
I sent Tarik and you the music.
Check your email for once.

**Comment by sylvia43** [comment]
Don't email it to me. Put it in the repo. Not hard.

**Comment by sylvia43** [comment]
That was a misclick.

**Pull request closed without merging**
