### PR TITLE
Fixed music loop

### PR DESCRIPTION
**Pull request by RobUnderscore**
Modified isPlaying() to check for music.getPosition() and see if the song was over. Modified playMusic() to accommodate.

### CODE REVIEW

**Comment by sylvia43** [comment]
Oh cool! Thanks a ton! I'll check it out in a bit and merge. Can I ask who you are?

**Comment by sylvia43** [comment]
Looks pretty good too, will test. BTW I think you're using tabs instead of spaces.

**Comment by RobUnderscore** [comment]
I'm just a guy looking to help out (and gain experience with!) Java projects. :)

Ahh, and sorry, I thought I switched it over to spaces, I guess I didn't.

**Comment by sylvia43** [comment]
Thanks for the help :smile: 

If you want to collaborate on something shoot me an email.

**Pull request merged**
