### PR TITLE
Make constants static final

### PR DESCRIPTION
**Pull request by kevinji**

### CODE REVIEW

**Comment by sylvia43** [comment]
These fields could be changed so I left them as unfinal and they are relative to the instance so I left the unstatic...

**Comment by kevinji** [comment]
If they could be changed, they shouldn't be `CONSTANTS` (and from what I see, they are not modified within the class, so `final` should be added). I don't think the constants are "relative to the instance" as they remain equal between instances of `Player`, so they should be `static` as well.

**Comment by sylvia43** [comment]
Currently they aren't being changed but that could be implemented. They are relative to the player instance; if there are multiple players then they could vary between them. Player should have a static factory and a private constructor though...

**Comment by sylvia43** [comment]
*will be implemented... But yeah they probably should be cleaned up somehow, they're kinda annoying right now...

**Pull request closed without merging**
